In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    "../data/raw/Fraud_Data.csv"
)

In [3]:
df["signup_time"] = pd.to_datetime(
    df["signup_time"]
)

df["purchase_time"] = pd.to_datetime(
    df["purchase_time"]
)

In [4]:
df["time_since_signup"] = (
    df["purchase_time"]
    -
    df["signup_time"]
).dt.total_seconds()

In [5]:
df["hour_of_day"] = (
    df["purchase_time"]
    .dt.hour
)

In [6]:
df["day_of_week"] = (
    df["purchase_time"]
    .dt.dayofweek
)

In [7]:
transaction_frequency = (
    df.groupby("user_id")
    .size()
    .reset_index(
        name="transaction_count"
    )
)

transaction_frequency.head()

   user_id  transaction_count
0        2                  1
1        4                  1
2        8                  1
3        9                  1
4       12                  1

In [8]:
country_df = pd.read_csv(
    "../data/raw/IpAddress_to_Country.csv"
)

country_df.head()

   lower_bound_ip_address  upper_bound_ip_address    country
0              16777216.0                16777471  Australia
1              16777472.0                16777727      China
2              16777728.0                16778239      China
3              16778240.0                16779263  Australia
4              16779264.0                16781311      China

In [9]:
df["ip_address"] = (
    df["ip_address"]
    .astype("int64")
)

## Resampling Strategy

The fraud datasets are highly imbalanced.

SMOTE will be applied during model training because it generates synthetic fraud examples and helps improve recall without discarding legitimate transactions.

Resampling will only be applied on training data to avoid data leakage.